### ISSUE TITLE
Pricing

### ISSUE THREAD

**Issue by ghost** [Andimated/prj-rev-bwfs-dasmoto#5]
https://github.com/Andimated/prj-rev-bwfs-dasmoto/blob/master/ArtStore/index.html#L25

Nice job using an inline tag like `strong` to write your price information 👍 

Give each `strong` tag the same class, like `price` or `cost`. This allows you to easily select the all the `strong` tags related to pricing and will prevent bugs in the future.

**Comment by Andimated** [comment]
Good pointer. Thank you!
