### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [Andimated/prj-rev-bwfs-dasmoto#6]
https://github.com/Andimated/prj-rev-bwfs-dasmoto/blob/master/ArtStore/resources/style.css#L15

When writing relative file paths, you need to write them _relative to the working file_, which, in this case, is `style.css`. 

Use this file path instead `"images/pattern.jpeg"`.

https://github.com/Andimated/prj-rev-bwfs-dasmoto/blob/master/ArtStore/resources/style.css#L1-L20

You shouldn't have to repeat the font-family style in every single CSS rule. Extract it into a single CSS rule with a more general selector, like `*` or `body`.

**Comment by Andimated** [comment]
Got it, thank you!
